# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://schadokar.dev/"
languageCode = "en"
defaultContentLanguage = "en"

title = "schadokar.dev"
copyright =  "&copy; <a href=\"https://schadokar.dev\">Shubham Chadokar</a> 2025"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

# version 4
googleAnalytics = "G-FQRDVY1Q17"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# content management
[permalinks]
  #enable = false
  posts = "/posts/:title/"
  to-the-point = "/to-the-point/:title/"

[params.author]
  name = "Shubham Chadokar"
  image = "images/pic3.jpg"
  bio = "I'm a software engineer and a learner. This is a documentation website of my learnings for my future self."
  links = [
    { email = "mailto:hello@schadokar.dev" },
    { twitter = "https://twitter.com/schadokar1" },
    { github = "https://github.com/schadokar" },
    { linkedin = "https://linkedin.com/in/schadokar" },
    { medium = "https://medium.com/@schadokar" },
  #  { youtube = "https://youtube.com/@practicego" },
  ]

  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },

  #   { mastodon = "https://mastodon.instance/@username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },

  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
