# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "youtube"
#  url = "https://youtube.com/@practicego"
#  weight = 10

[[main]]
  name = "blog"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "to the point"
  pageRef = "to-the-point"
  weight = 30

#[[main]]
#  name = "about me"
#  pageRef = "about"
#  weight = 40

#[[main]]
#  name = "newsletter"
#  url = "https://schadokar.substack.com"
#  weight = 30

[[main]]
  name = "archive"
  url = "https://schadokar.github.io/archive/"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#[[footer]]
#  name = "archive"
#  pageRef = "https://schadokar.github.io/archive/"
#  weight = 10
