baseurl = "https://schadokar.dev"
languageCode = "en"
title = "Shubham Chadokar"
theme = "hugo-notepadium"
copyright = "&copy; <a href=\"https://schadokar.dev\">Shubham Chadokar</a> 2020"
disqusShortname = "schadokar"
googleAnalytics = "UA-158088106-1"

enableInlineShortcodes= true

# Number of posts per page
Paginate = 10
enableRobotsTXT = true
enableEmoji=true

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"


[[params.nav.custom]]
title = "Posts"
url = "/posts"

[[params.nav.custom]]
title = "To-The-Point"
url = "/to-the-point"

[[params.nav.custom]]
title = "Projects"
url = "/projects"

[[params.nav.custom]]
title = "Ebook"
url = "/ebooks"

[[params.nav.custom]]
title = "About"
url = "/about"
