baseurl = "https://schadokar.dev"
languageCode = "en"
title = "Shubham Chadokar"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/schadokar\">Shubham Chadokar</a> 2020"
disqusShortname = "schadokar"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
enableEmoji=true

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Shubham Chadokar" # Site author's full name
authorEmail = "shubhamchadokar04@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "schadokar1"
github = "schadokar"
email = "shubhamchadokar04@gmail.com"
linkedin = "schadokar"
gitlab = "schadokar"
instagram = ""
codepen = ""
facebook = ""



[params.social.config]
platforms = ["github","email","linkedin","twitter"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

